//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBiQuickCreateDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBiQuickCreateDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section Section1; 
        ///shared Table = let
        ///    Source = Csv.Document(Web.Contents(&quot;https://github.com/PowerBiDevCamp/PowerBiQuickCreateDemo/raw/main/Data/Countries.csv&quot;),[Delimiter=&quot;,&quot;, Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
        ///    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
        ///    ChangedType = Table.TransformColumnTypes(PromotedHeaders,{{&quot;Population&quot;, Int64.Type}, {&quot;Urban Population&quot;, Percentage.Type}, {&quot;Land Size&quot;, Int64.Type}, {&quot;Poupulation Density&quot;, type number} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountriesQuery_m {
            get {
                return ResourceManager.GetString("CountriesQuery_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section Section1;
        ///
        ///shared Table = let
        ///    Source = Csv.Document(Web.Contents(&quot;https://github.com/PowerBiDevCamp/PowerBiQuickCreateDemo/raw/main/Data/Expenses.csv&quot;),[Delimiter=&quot;,&quot;, Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
        ///    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
        ///    ChangedType = Table.TransformColumnTypes(PromotedHeaders,{{&quot;Expense&quot;, type text}, {&quot;Category&quot;, type text}, {&quot;Date&quot;, type date}, {&quot;Amount&quot;, Currency.Type}})
        ///in
        ///    ChangedType;.
        /// </summary>
        internal static string ExpensesQuery_m {
            get {
                return ResourceManager.GetString("ExpensesQuery_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section Section1;
        ///
        ///shared Table = let
        ///    RosterUrl = &quot;[NFL_ROSTER_URL]&quot;,
        ///    Source = Web.Contents(RosterUrl),
        ///    ExtractedHtmlTable = Html.Table(
        ///        Source,
        ///        {
        ///            {&quot;Column1&quot;, &quot;th:nth-child(1), td:nth-child(1)&quot;},
        ///            {&quot;Column2&quot;, &quot;th:nth-child(2), td:nth-child(2)&quot;},
        ///            {&quot;Column3&quot;, &quot;th:nth-child(3), td:nth-child(3)&quot;},
        ///            {&quot;Column4&quot;, &quot;th:nth-child(4), td:nth-child(4)&quot;},
        ///            {&quot;Column5&quot;, &quot;th:nth-child(5), td:nth-child(5)&quot;},
        ///            {&quot;Colum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NFLRosterQuery_m {
            get {
                return ResourceManager.GetString("NFLRosterQuery.m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section Section1; 
        ///
        ///shared Table = let    
        ///  Source = Web.Contents(&quot;https://en.wikipedia.org/wiki/List_of_highest-grossing_films&quot;),
        ///  ExtractedTableFromHtml = Html.Table(Source, 
        ///    {
        ///      {&quot;Column1&quot;, &quot;TABLE.wikitable.sortable.plainrowheaders &gt; * &gt; TR &gt; :nth-child(1)&quot;}, 
        ///      {&quot;Column2&quot;, &quot;TABLE.wikitable.sortable.plainrowheaders &gt; * &gt; TR &gt; :nth-child(2)&quot;}, 
        ///      {&quot;Column3&quot;, &quot;TABLE.wikitable.sortable.plainrowheaders &gt; * &gt; TR &gt; :nth-child(3)&quot;}, 
        ///      {&quot;Column4&quot;, &quot;TABLE.wikitable.sortable.plainro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WikipediaQuery_m {
            get {
                return ResourceManager.GetString("WikipediaQuery.m", resourceCulture);
            }
        }
    }
}
